
# templates_dir: /home/guilherme/projects/parai/data/templates/df_templates_dlib
# framework: deepface

templates_dir: /home/guilherme/projects/parai/data/templates/fr_templates
framework: face_recognition

